---
############################################################
# Install containerd
############################################################

- name: Install containerd
  ansible.builtin.dnf:
    name:
      - containerd
    state: present

############################################################
# Create containerd configuration
############################################################

- name: Create containerd configuration directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Generate default containerd configuration
  ansible.builtin.shell:
    cmd: containerd config default > /etc/containerd/config.toml
    creates: /etc/containerd/config.toml

############################################################
# Configure systemd cgroups
############################################################

- name: Configure containerd to use systemd cgroups
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'

############################################################
# Start containerd
############################################################

- name: Enable containerd
  ansible.builtin.systemd:
    name: containerd
    enabled: true
    state: restarted

- name: Verify containerd
  ansible.builtin.command:
    cmd: systemctl is-active containerd
  register: containerd_status
  changed_when: false

- name: Display containerd status
  ansible.builtin.debug:
    var: containerd_status.stdout
