---
############################################################
# Install Calico
############################################################

- name: Install Calico operator
  ansible.builtin.command:
    cmd: >
      kubectl apply
      -f https://raw.githubusercontent.com/projectcalico/calico/master/manifests/tigera-operator.yaml
    environment:
      KUBECONFIG: /etc/kubernetes/admin.conf
  delegate_to: "{{ groups['control_plane'][0] }}"
  run_once: true
  changed_when: true

############################################################
# Install Calico Custom Resources
############################################################

- name: Download Calico custom resources
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/projectcalico/calico/master/manifests/custom-resources.yaml
    dest: /tmp/calico-custom-resources.yaml
    mode: '0644'
  delegate_to: "{{ groups['control_plane'][0] }}"
  run_once: true

- name: Configure Calico CIDR
  ansible.builtin.replace:
    path: /tmp/calico-custom-resources.yaml
    regexp: '192\.168\.0\.0/16'
    replace: "{{ pod_network_cidr }}"
  delegate_to: "{{ groups['control_plane'][0] }}"
  run_once: true

- name: Apply Calico custom resources
  ansible.builtin.command:
    cmd: kubectl apply -f /tmp/calico-custom-resources.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  delegate_to: "{{ groups['control_plane'][0] }}"
  run_once: true
  changed_when: true
