---
############################################################
# Check worker state
############################################################

- name: Check whether worker is already joined
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_config

############################################################
# Join worker to cluster
############################################################

- name: Join worker node to Kubernetes cluster
  ansible.builtin.command:
    cmd: "{{ hostvars[groups['control_plane'][0]].kubeadm_join_command }}"
  when: not kubelet_config.stat.exists
  register: worker_join
  changed_when: true
